




.build/mega2560/src/sketch/sketch.cpp : src/sketch/sketch.ino
	@mkdir -p .build/mega2560/src/sketch
	@echo [93msrc/sketch/sketch.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/mega2560/src/sketch/sketch.cpp
	@true

