




.build/mega2560/src/Seeding.cpp : src/Seeding.ino
	@mkdir -p .build/mega2560/src
	@echo [93msrc/Seeding.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/mega2560/src/Seeding.cpp
	@true

