




.build/mega2560/src/Test_GRAB.cpp : src/Test_GRAB.ino
	@mkdir -p .build/mega2560/src
	@echo [93msrc/Test_GRAB.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/mega2560/src/Test_GRAB.cpp
	@true

